import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styled, { keyframes } from "styled-components";
import Link from "next/link";
// import styles from "../styles/Home.module.css";

const rotate = keyframes`
  from {
    transform: rotate(360deg);
  }
  to {
    transform: rotate(0deg);
  }
`;

const Container = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  padding: 6rem;
  min-height: 100vh;
`;

const DescriptionArea = styled.div`
  display: inherit;
  justify-content: inherit;
  align-items: inherit;
  font-size: 0.85rem;
  max-width: ${({ theme: { home } }) => home.maxWidth};
  width: 100%;
  z-index: 2;
  font-family: ${({ theme: { home } }) => home.fontMono};

  a {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 0.5rem;
  }

  p {
    position: relative;
    margin: 0;
    padding: 1rem;
    background-color: ${({ theme: { home } }) =>
      `rgba(${home.calloutRgb}, 0.5)`};
    border: ${({ theme: { home } }) =>
      `1px solid rgba(${home.calloutBorderRgb}, 0.3)`};
    border-radius: ${({ theme: { home } }) => home.borderRadius};
  }
`;

const CodeArea = styled.code`
  font-weight: 700;
  font-family: ${({ theme: { home } }) => home.fontMono};
`;

const GridArea = styled.div`
  display: grid;
  grid-template-columns: repeat(4, minmax(25%, auto));
  width: ${({ theme: { home } }) => home.maxWidth};
  max-width: 100%;
`;

const CardArea = styled.a`
  padding: 1rem 1.2rem;
  border-radius: ${({ theme: { home } }) => home.borderRadius};
  background-color: ${({ theme: { home } }) => `rgba(${home.cardRgb}, 0)`};
  border: ${({ theme: { home } }) =>
    `1px solid rgba(${home.cardBorderRgb}, 0)`};
  transition: background 200ms, border 200ms;

  span {
    display: inline-block;
    transition: transform 200ms;
  }

  h2 {
    font-weight: 600;
    margin-bottom: 0.7rem;
  }

  p {
    margin: 0;
    opacity: 0.6;
    font-size: 0.9rem;
    line-height: 1.5;
    max-width: 30ch;
  }

  @media (hover: hover) and (pointer: fine) {
    :hover {
      background-color: ${({ theme: { home } }) =>
        `rgba(${home.cardRgb}, 0.1)`};
      border: ${({ theme: { home } }) =>
        `1px solid rgba(${home.cardBorderRgb}, 0.15)`};

      span {
        transform: translateX(4px);
      }
    }
  }

  @media (prefers-reduced-motion) {
    :hover {
      span {
        transform: none;
      }
    }
  }

  @media (max-width: 700px) {
    padding: 1rem 2.5rem;

    h2 {
      margin-bottom: 0.5rem;
    }
  }
`;

const CenterArea = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
  padding: 4rem 0;

  ::after {
    background: ${({ theme: { home } }) => home.primaryGlow};
    width: 240px;
    height: 180px;
    z-index: -1;
  }

  ::before,
  ::after {
    content: "";
    left: 50%;
    position: absolute;
    filter: blur(45px);
    transform: translateZ(0);
  }

  cursor: pointer;
`;

const VersionArea = styled.div`
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 75px;
  height: 75px;
  padding: 25px 10px;
  margin-left: 16px;
  transform: translateZ(0);
  border-radius: ${({ theme: { home } }) => home.borderRadius};
  overflow: hidden;
  box-shadow: 0px 2px 8px -1px #0000001a;

  ::before,
  ::after {
    content: "";
    position: absolute;
    z-index: -1;
  }

  ::before {
    animation: 6s ${rotate} linear infinite;
    width: 200%;
    height: 200%;
    background: ${({ theme: { home } }) => home.tileBorder};
  }

  ::after {
    inset: 0;
    padding: 1px;
    border-radius: ${({ theme: { home } }) => home.borderRadius};
    background: ${({ theme: { home } }) =>
      `linear-gradient(to bottom right, rgba(${home.tileStartRgb}, 1), rgba(${home.tileEndRgb}, 1))`};
    background-clip: content-box;
  }

  @media (prefers-reduced-motion) {
    ::before {
      animation: none;
    }
  }

  /* @media (prefers-color-scheme: dark) {
    img {
      filter: invert(1) drop-shadow(0 0 0.3rem #ffffff70);
    }
  } */
`;

const NextLogo = styled(Image)`
  position: relative;

  /* @media (prefers-color-scheme: dark) {
    filter: invert(1) drop-shadow(0 0 0.3rem #ffffff70);
  } */
`;

const VercelLogo = styled(Image)`
  /* @media (prefers-color-scheme: dark) {
    filter: invert(1);
  } */
`;

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/favicon.ico" />
      </Head>
      <Container>
        <DescriptionArea>
          <p>
            Get started by editing&nbsp;
            <CodeArea>pages/index.tsx</CodeArea>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <VercelLogo
                src="images/vercel.svg"
                alt="Vercel Logo"
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </DescriptionArea>

        <Link href="/sample">
          <CenterArea>
            <NextLogo
              // className={styles.logo}
              src="images/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
            <VersionArea>
              <Image
                src="images/thirteen.svg"
                alt="13"
                width={40}
                height={31}
                priority
              />
            </VersionArea>
          </CenterArea>
        </Link>

        <GridArea>
          <CardArea
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </CardArea>

          <CardArea
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </CardArea>

          <CardArea
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </CardArea>

          <CardArea
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </CardArea>
        </GridArea>
      </Container>
    </>
  );
}
